site_name: Cours Deep Learning
site_description: "ğŸš€ Apprendre le Deep Learning Ã  partir de zÃ©ro ğŸš€"
site_url: "https://SimonThomine.github.io/CoursDeepLearning"
repo_url: "https://github.com/SimonThomine/CoursDeepLearning"
repo_name: "SimonThomine/CoursDeepLearning"
docs_dir: ./cours
copyright: Copyright &copy; 2024 Simon Thomine
site_author: Simon Thomine

nav:
  - ğŸ  Accueil: README.md

  - ğŸ§® Fondations:
    - DÃ©rivÃ©es de descente du gradient: 01_Fondations/01_DÃ©rivÃ©esEtDescenteDuGradient.ipynb
    - RÃ©gression Logistique: 01_Fondations/02_RÃ©gressionLogistique.ipynb
    - ğŸ“ QCM: 01_Fondations/qcm.html
  
  - ğŸ”— RÃ©seau Fully Connected:
    - Mon premier rÃ©seau: 02_RÃ©seauFullyConnected/01_MonPremierRÃ©seau.ipynb
    - Pytorch introduction: 02_RÃ©seauFullyConnected/02_PytorchIntroduction.ipynb
    - Techniques avancÃ©es: 02_RÃ©seauFullyConnected/03_TechniquesAvancÃ©es.ipynb
    - ğŸ“ QCM: 02_RÃ©seauFullyConnected/qcm.html

  - ğŸ–¼ï¸ RÃ©seau Convolutifs:
    - Couches de convolutions: 03_RÃ©seauConvolutifs/01_CouchesDeConvolutions.ipynb
    - RÃ©seau Convolutif: 03_RÃ©seauConvolutifs/02_RÃ©seauConvolutif.ipynb
    - Conv Implementation: 03_RÃ©seauConvolutifs/03_ConvImplementation.ipynb
    - RÃ©seau Convolutif Pytorch: 03_RÃ©seauConvolutifs/04_RÃ©seauConvolutifPytorch.ipynb
    - Application Classification: 03_RÃ©seauConvolutifs/05_ApplicationClassification.ipynb
    - Application Segmentation: 03_RÃ©seauConvolutifs/06_ApplicationSegmentation.ipynb
    - ğŸ“ QCM: 03_RÃ©seauConvolutifs/qcm.html

  - ğŸ”„ Autoencodeurs:
    - Intuition et premier AE: 04_Autoencodeurs/01_IntuitionEtPremierAE.ipynb
    - Denoising AE: 04_Autoencodeurs/02_DenoisingAE.ipynb
    - ğŸ“ QCM: 04_Autoencodeurs/qcm.html

  - ğŸ“ NLP:
    - Introduction: 05_NLP/01_Introduction.ipynb
    - Bigramme: 05_NLP/02_bigramme.ipynb
    - RÃ©seau Fully Connected: 05_NLP/03_RÃ©seauFullyConnected.ipynb
    - WaveNet: 05_NLP/04_WaveNet.ipynb
    - RNN: 05_NLP/05_Rnn.ipynb
    - LSTM: 05_NLP/06_Lstm.ipynb
    - ğŸ“ QCM: 05_NLP/qcm.html

  - ğŸ¤— HuggingFace:
    - Introduction: 06_HuggingFace/01_introduction.ipynb
    - Computer vision with transformers: 06_HuggingFace/02_ComputerVisionWithTransformers.ipynb
    - NLP with transformers: 06_HuggingFace/03_NlpWithTransformers.ipynb
    - Audio with transformers: 06_HuggingFace/04_AudioWithTransformers.ipynb
    - Image generation with diffusers: 06_HuggingFace/05_ImageGenerationWithDiffusers.ipynb
    - Demo avec gradio: 06_HuggingFace/06_DemoAvecGradio.ipynb

  - âš¡ Transformers:
    - Introduction: 07_Transformers/01_Introduction.ipynb
    - GPT from scratch: 07_Transformers/02_GptFromScratch.ipynb
    - Training our GPT: 07_Transformers/03_TrainingOurGpt.ipynb
    - Architecture et particularitÃ©s: 07_Transformers/04_ArchitectureEtParticularitÃ©s.ipynb
    - Utilisations possibles: 07_Transformers/05_UtilisationsPossibles.ipynb
    - Vision Transformer Implementation: 07_Transformers/06_VisionTransformerImplementation.ipynb
    - Swin Transformer: 07_Transformers/07_SwinTransformer.ipynb
    - ğŸ“ QCM: 07_Transformers/qcm.html

  - ğŸ¯ Detection Et Yolo:
    - Introduction: 08_DetectionEtYolo/01_Introduction.ipynb
    - Yolo en dÃ©tail: 08_DetectionEtYolo/02_YoloEnDetail.ipynb
    - Ultralytics: 08_DetectionEtYolo/03_Ultralytics.ipynb
    - ğŸ“ QCM: 08_DetectionEtYolo/qcm.html
  
  - ğŸ” Entrainement Contrastif:
    - Face verification: 09_EntrainementContrastif/01_FaceVerification.ipynb
    - Non supervisÃ©: 09_EntrainementContrastif/02_NonSupervisÃ©.ipynb
    - ğŸ“ QCM: 09_EntrainementContrastif/qcm.html

  - ğŸ“ Transfer Learning Et Distillation:
    - Transfer learning: 10_TransferLearningEtDistillation/01_TransferLearning.ipynb
    - Transfer learning pytorch: 10_TransferLearningEtDistillation/02_TransferLearningPytorch.ipynb
    - Distillation: 10_TransferLearningEtDistillation/03_Distillation.ipynb
    - Distillation Anomalie: 10_TransferLearningEtDistillation/04_DistillationAnomalie.ipynb
    - Fine Tuning LLM: 10_TransferLearningEtDistillation/05_FineTuningLLM.ipynb
    - Fine Tuning Bert HF: 10_TransferLearningEtDistillation/06_FineTuningBertHF.ipynb
    - ğŸ“ QCM: 10_TransferLearningEtDistillation/qcm.html

  - ğŸ¨ Modeles Generatifs:
    - Introduction: 11_ModelesGeneratifs/01_Introduction.ipynb
    - GAN: 11_ModelesGeneratifs/02_GAN.ipynb
    - Gan Implementation: 11_ModelesGeneratifs/03_GanImplementation.ipynb
    - VAE: 11_ModelesGeneratifs/04_VAE.ipynb
    - Vae Implementation: 11_ModelesGeneratifs/05_VaeImplementation.ipynb
    - Normalizing Flows: 11_ModelesGeneratifs/06_NormalizingFlows.ipynb
    - Diffusion Models: 11_ModelesGeneratifs/07_DiffusionModels.ipynb
    - Diffusion Implementation: 11_ModelesGeneratifs/08_DiffusionImplementation.ipynb
    - ğŸ“ QCM: 11_ModelesGeneratifs/qcm.html

  - ğŸ Bonus Cours SpÃ©cifiques:
    - âœ¨ Activation et initialisation:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/01_ActivationEtInitialisation.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_01_ActivationEtInitialisation.html
    - ğŸ“Š BatchNorm:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/02_BatchNorm.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_02_BatchNorm.html
    - ğŸ”„ Data augmentation:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/03_DataAugmentation.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_03_DataAugmentation.html
    - ğŸ“¡ Broadcasting:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/04_Broadcasting.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_04_Broadcasting.html
    - ğŸš€ Optimizer:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/05_Optimizer.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_05_Optimizer.html
    - ğŸ›¡ï¸ RÃ©gularisation:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/06_Regularisation.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_06_Regularisation.html
    - ğŸ”— Connexions RÃ©siduelles:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/07_ConnexionsResiduelles.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_07_ConnexionsResiduelles.html
    - âœ… CrossValidation:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/08_CrossValidation.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_08_CrossValidation.html
    - ğŸ“ MÃ©triques Evaluation:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/09_MetriquesEvaluation.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_09_MetriquesEvaluation.html
    - ğŸ”¤ Tokenization:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/10_Tokenization.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_10_Tokenization.html
    - âš›ï¸ Quantization:
      - ğŸ“– Cours: Bonus_CoursSpÃ©cifiques/11_Quantization.ipynb
      - ğŸ“ QCM: Bonus_CoursSpÃ©cifiques/qcm_11_Quantization.html


theme:
  name: material
  language: fr
  icon:
    logo: material/rocket-launch
  # favicon: images/favicon.ico
  palette: 
    # Auto mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.logo_text
    
plugins:
  - mkdocs-jupyter:
      execute: False
      include_source: True
  - search

use_directory_urls: false

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css