site_name: Cours Deep Learning
site_description: "ğŸš€ Apprendre le Deep Learning Ã  partir de zÃ©ro ğŸš€"
site_url: "https://SimonThomine.github.io/CoursDeepLearning"
repo_url: "https://github.com/SimonThomine/CoursDeepLearning"
repo_name: "SimonThomine/CoursDeepLearning"
docs_dir: ./cours
copyright: Copyright &copy; 2024 Simon Thomine
site_author: Simon Thomine

nav:
  - ğŸ  Accueil: fr/README.md

  - ğŸ§® Fondations:
    - DÃ©rivÃ©es de descente du gradient: fr/01_Fondations/01_DÃ©rivÃ©esEtDescenteDuGradient.ipynb
    - RÃ©gression Logistique: fr/01_Fondations/02_RÃ©gressionLogistique.ipynb
    - ğŸ“ QCM: fr/01_Fondations/qcm.html

  - ğŸ”— RÃ©seau Fully Connected:
    - Mon premier rÃ©seau: fr/02_RÃ©seauFullyConnected/01_MonPremierRÃ©seau.ipynb
    - Pytorch introduction: fr/02_RÃ©seauFullyConnected/02_PytorchIntroduction.ipynb
    - Techniques avancÃ©es: fr/02_RÃ©seauFullyConnected/03_TechniquesAvancÃ©es.ipynb
    - ğŸ“ QCM: fr/02_RÃ©seauFullyConnected/qcm.html

  - ğŸ–¼ï¸ RÃ©seau Convolutifs:
    - Couches de convolutions: fr/03_RÃ©seauConvolutifs/01_CouchesDeConvolutions.ipynb
    - RÃ©seau Convolutif: fr/03_RÃ©seauConvolutifs/02_RÃ©seauConvolutif.ipynb
    - Conv Implementation: fr/03_RÃ©seauConvolutifs/03_ConvImplementation.ipynb
    - RÃ©seau Convolutif Pytorch: fr/03_RÃ©seauConvolutifs/04_RÃ©seauConvolutifPytorch.ipynb
    - Application Classification: fr/03_RÃ©seauConvolutifs/05_ApplicationClassification.ipynb
    - Application Segmentation: fr/03_RÃ©seauConvolutifs/06_ApplicationSegmentation.ipynb
    - ğŸ“ QCM: fr/03_RÃ©seauConvolutifs/qcm.html

  - ğŸ”„ Autoencodeurs:
    - Intuition et premier AE: fr/04_Autoencodeurs/01_IntuitionEtPremierAE.ipynb
    - Denoising AE: fr/04_Autoencodeurs/02_DenoisingAE.ipynb
    - ğŸ“ QCM: fr/04_Autoencodeurs/qcm.html

  - ğŸ“ NLP:
    - Introduction: fr/05_NLP/01_Introduction.ipynb
    - Bigramme: fr/05_NLP/02_bigramme.ipynb
    - RÃ©seau Fully Connected: fr/05_NLP/03_RÃ©seauFullyConnected.ipynb
    - WaveNet: fr/05_NLP/04_WaveNet.ipynb
    - RNN: fr/05_NLP/05_Rnn.ipynb
    - LSTM: fr/05_NLP/06_Lstm.ipynb
    - ğŸ“ QCM: fr/05_NLP/qcm.html

  - ğŸ¤— HuggingFace:
    - Introduction: fr/06_HuggingFace/01_introduction.ipynb
    - Computer vision with transformers: fr/06_HuggingFace/02_ComputerVisionWithTransformers.ipynb
    - NLP with transformers: fr/06_HuggingFace/03_NlpWithTransformers.ipynb
    - Audio with transformers: fr/06_HuggingFace/04_AudioWithTransformers.ipynb
    - Image generation with diffusers: fr/06_HuggingFace/05_ImageGenerationWithDiffusers.ipynb
    - Demo avec gradio: fr/06_HuggingFace/06_DemoAvecGradio.ipynb

  - âš¡ Transformers:
    - Introduction: fr/07_Transformers/01_Introduction.ipynb
    - GPT from scratch: fr/07_Transformers/02_GptFromScratch.ipynb
    - Training our GPT: fr/07_Transformers/03_TrainingOurGpt.ipynb
    - Architecture et particularitÃ©s: fr/07_Transformers/04_ArchitectureEtParticularitÃ©s.ipynb
    - Utilisations possibles: fr/07_Transformers/05_UtilisationsPossibles.ipynb
    - Vision Transformer Implementation: fr/07_Transformers/06_VisionTransformerImplementation.ipynb
    - Swin Transformer: fr/07_Transformers/07_SwinTransformer.ipynb
    - ğŸ“ QCM: fr/07_Transformers/qcm.html

  - ğŸ¯ Detection Et Yolo:
    - Introduction: fr/08_DetectionEtYolo/01_Introduction.ipynb
    - Yolo en dÃ©tail: fr/08_DetectionEtYolo/02_YoloEnDetail.ipynb
    - Ultralytics: fr/08_DetectionEtYolo/03_Ultralytics.ipynb
    - ğŸ“ QCM: fr/08_DetectionEtYolo/qcm.html

  - ğŸ” Entrainement Contrastif:
    - Face verification: fr/09_EntrainementContrastif/01_FaceVerification.ipynb
    - Non supervisÃ©: fr/09_EntrainementContrastif/02_NonSupervisÃ©.ipynb
    - ğŸ“ QCM: fr/09_EntrainementContrastif/qcm.html

  - ğŸ“ Transfer Learning Et Distillation:
    - Transfer learning: fr/10_TransferLearningEtDistillation/01_TransferLearning.ipynb
    - Transfer learning pytorch: fr/10_TransferLearningEtDistillation/02_TransferLearningPytorch.ipynb
    - Distillation: fr/10_TransferLearningEtDistillation/03_Distillation.ipynb
    - Distillation Anomalie: fr/10_TransferLearningEtDistillation/04_DistillationAnomalie.ipynb
    - Fine Tuning LLM: fr/10_TransferLearningEtDistillation/05_FineTuningLLM.ipynb
    - Fine Tuning Bert HF: fr/10_TransferLearningEtDistillation/06_FineTuningBertHF.ipynb
    - ğŸ“ QCM: fr/10_TransferLearningEtDistillation/qcm.html

  - ğŸ¨ Modeles Generatifs:
    - Introduction: fr/11_ModelesGeneratifs/01_Introduction.ipynb
    - GAN: fr/11_ModelesGeneratifs/02_GAN.ipynb
    - Gan Implementation: fr/11_ModelesGeneratifs/03_GanImplementation.ipynb
    - VAE: fr/11_ModelesGeneratifs/04_VAE.ipynb
    - Vae Implementation: fr/11_ModelesGeneratifs/05_VaeImplementation.ipynb
    - Normalizing Flows: fr/11_ModelesGeneratifs/06_NormalizingFlows.ipynb
    - Diffusion Models: fr/11_ModelesGeneratifs/07_DiffusionModels.ipynb
    - Diffusion Implementation: fr/11_ModelesGeneratifs/08_DiffusionImplementation.ipynb
    - ğŸ“ QCM: fr/11_ModelesGeneratifs/qcm.html

  - ğŸ Bonus Cours SpÃ©cifiques:
    - âœ¨ Activation et initialisation:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/01_ActivationEtInitialisation.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_01_ActivationEtInitialisation.html
    - ğŸ“Š BatchNorm:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/02_BatchNorm.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_02_BatchNorm.html
    - ğŸ”„ Data augmentation:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/03_DataAugmentation.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_03_DataAugmentation.html
    - ğŸ“¡ Broadcasting:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/04_Broadcasting.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_04_Broadcasting.html
    - ğŸš€ Optimizer:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/05_Optimizer.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_05_Optimizer.html
    - ğŸ›¡ï¸ RÃ©gularisation:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/06_Regularisation.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_06_Regularisation.html
    - ğŸ”— Connexions RÃ©siduelles:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/07_ConnexionsResiduelles.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_07_ConnexionsResiduelles.html
    - âœ… CrossValidation:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/08_CrossValidation.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_08_CrossValidation.html
    - ğŸ“ MÃ©triques Evaluation:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/09_MetriquesEvaluation.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_09_MetriquesEvaluation.html
    - ğŸ”¤ Tokenization:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/10_Tokenization.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_10_Tokenization.html
    - âš›ï¸ Quantization:
      - ğŸ“– Cours: fr/Bonus_CoursSpÃ©cifiques/11_Quantization.ipynb
      - ğŸ“ QCM: fr/Bonus_CoursSpÃ©cifiques/qcm_11_Quantization.html

theme:
  name: material
  language: fr
  icon:
    logo: material/rocket-launch
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.logo_text
    
plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      default_language: fr
      languages:
        fr:
          name: FranÃ§ais
          build: true
        en:
          name: English
          build: true
          nav_translations:
            ğŸ  Accueil: ğŸ  Home
            ğŸ§® Fondations: ğŸ§® Foundations
            ğŸ”— RÃ©seau Fully Connected: ğŸ”— Fully Connected Network
            ğŸ–¼ï¸ RÃ©seau Convolutifs: ğŸ–¼ï¸ Convolutional Networks
            ğŸ”„ Autoencodeurs: ğŸ”„ Autoencoders
            ğŸ“ NLP: ğŸ“ NLP
            ğŸ¤— HuggingFace: ğŸ¤— HuggingFace
            âš¡ Transformers: âš¡ Transformers
            ğŸ¯ Detection Et Yolo: ğŸ¯ Detection And Yolo
            ğŸ” Entrainement Contrastif: ğŸ” Contrastive Training
            ğŸ“ Transfer Learning Et Distillation: ğŸ“ Transfer Learning And Distillation
            ğŸ¨ Modeles Generatifs: ğŸ¨ Generative Models
            ğŸ Bonus Cours SpÃ©cifiques: ğŸ Bonus Specific Courses
  - mkdocs-jupyter:
      execute: False
      include_source: True
  - search
      
docs_dir: ./cours
use_directory_urls: false

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 0

extra:
  alternate:
    - name: FranÃ§ais
      link: /CoursDeepLearning/fr/ 
      lang: fr
    - name: English
      link: /CoursDeepLearning/en/
      lang: en

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css